= Policy: `default-rolebinding-in-ns`

[horizontal]
Category:: Access Control
Minimum Kyverno version:: v1
subject:: rbac
Policy type:: "generate"
Implementation:: https://github.com/appuio/component-appuio-cloud/tree/master/component/generated-rolebindings.jsonnet[component/generated-rolebindings.jsonnet]

This policy will:

- Generate a RoleBinding to ClusterRole 'admin' for the organization defined in a label of a namespace.
- For namespaces created through a project, it mutates the `admin` RoleBinding to reference the organization instead of the creating user.
- Generate a RoleBinding and Role 'namespace-owner' for the organization defined in a label of a namespace, which allows the edit and delete the namespace.
- Namespaces that do not have the 'appuio.io/organization' label are not affected.
- The RoleBinding is only created upon Namespace creation.
- Also, the RoleBinding is mutable by the user.


== Policy Definition

.https://github.com/appuio/component-appuio-cloud/tree/master//tests/golden/defaults/appuio-cloud/appuio-cloud/10_generate_default_rolebinding_in_ns.yaml[/tests/golden/defaults/appuio-cloud/appuio-cloud/10_generate_default_rolebinding_in_ns.yaml,window=_blank]
[source,yaml]
----
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  annotations:
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/category: Access Control
    policies.kyverno.io/description: 'This policy will:


      - Generate a RoleBinding to ClusterRole ''admin'' for the organization defined
      in a label of a namespace.

      - For namespaces created through a project, it mutates the `admin` RoleBinding
      to reference the organization instead of the creating user.

      - Generate a RoleBinding and Role ''namespace-owner'' for the organization defined
      in a label of a namespace, which allows the edit and delete the namespace.

      - Namespaces that do not have the ''appuio.io/organization'' label are not affected.

      - The RoleBinding is only created upon Namespace creation.

      - Also, the RoleBinding is mutable by the user.

      '
    policies.kyverno.io/jsonnet: component/generated-rolebindings.jsonnet
    policies.kyverno.io/minversion: v1
    policies.kyverno.io/subject: rbac
    policies.kyverno.io/title: Create default namespace ownership RoleBinding
  labels:
    app.kubernetes.io/component: appuio-cloud
    app.kubernetes.io/managed-by: commodore
    app.kubernetes.io/name: appuio-cloud
    name: default-rolebinding-in-ns
  name: default-rolebinding-in-ns
spec:
  rules:
    - generate:
        data:
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: admin
          subjects:
            - kind: Group
              name: '{{request.object.metadata.labels."appuio.io/organization"}}'
        kind: RoleBinding
        name: admin
        namespace: '{{request.object.metadata.name}}'
        synchronize: false
      match:
        all:
          - resources:
              kinds:
                - Namespace
              selector:
                matchExpressions:
                  - key: appuio.io/organization
                    operator: Exists
      name: default-rolebinding
    - context:
        - apiCall:
            jmesPath: metadata.labels."appuio.io/organization"
            urlPath: /api/v1/namespaces/{{request.object.metadata.namespace}}
          name: organization
      match:
        all:
          - resources:
              kinds:
                - rbac.authorization.k8s.io/v1/RoleBinding
              names:
                - admin
              selector:
                matchLabels:
                  appuio.io/uninitialized: 'true'
      mutate:
        patchesJson6902: "- \"name\": \"update-rolebinding\"\n  \"op\": \"add\"\n\
          \  \"path\": \"/subjects\"\n  \"value\":\n  - \"apiGroup\": \"rbac.authorization.k8s.io\"\
          \n    \"kind\": \"Group\"\n    \"name\": \"{{organization}}\"\n- \"op\"\
          : \"remove\"\n  \"path\": \"/metadata/labels/appuio.io~1uninitialized\""
      name: patch-uninitialized-default-rolebinding
    - generate:
        data:
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: namespace-owner
          subjects:
            - kind: Group
              name: '{{request.object.metadata.labels."appuio.io/organization"}}'
        kind: RoleBinding
        name: namespace-owner
        namespace: '{{request.object.metadata.name}}'
        synchronize: false
      match:
        all:
          - resources:
              kinds:
                - Namespace
              selector:
                matchExpressions:
                  - key: appuio.io/organization
                    operator: Exists
      name: namespace-edit-rolebinding

----
