:global:
  componentName: appuio-cloud
  githubUrl: https://github.com/appuio/component-appuio-cloud
  feature_goUnitTests: false
  feature_goldenTests: true

docs/antora.yml:
  name: appuio-cloud
  title: appuio-cloud

.gitignore:
  additionalEntries:
    - jsonnetfile.json
