:global:
  componentName: appuio-cloud
  githubUrl: https://github.com/appuio/component-appuio-cloud
  feature_goUnitTests: false
  feature_goldenTests: true

Makefile:
  includes:
    - Makefile.kyverno.mk

.gitignore:
  additionalEntries:
    - jsonnetfile.json
    - tests/kyverno/*/compiled
    - tools/render/render
