= Parameters

The parent key for all of the following parameters is `appuio_cloud`.

== `namespace`

[horizontal]
type:: string
default:: `syn-appuio-cloud`

The namespace in which to deploy this component.

== `reservedNamespaces`

[horizontal]
type:: dict
example::
+
[source,yaml]
----
reservedNamespaces:
  monitoring: ['monitoring-*', 'test-monitoring-*']
  logging: logging
----

Creating and editing namespaces matching any of the entries is disallowed.
The list must consist of entries like `custom: ['custom-*', 'test-custom-*']` or `custom: 'custom-*'`.

== `bypassNamespaceRestrictions.roles`

[horizontal]
type:: dict
example::
+
[source,yaml]
----
roles:
  my-admin: ['my-admin', 'test-admin']
  special-role: special-role
----

`Roles` in the same namespace excluded from all namespace policies.
Must consist of entries like `my-admin: ['my-admin', 'test-admin']` or `my-admin: 'my-admin'`.

== `bypassNamespaceRestrictions.clusterRoles`

[horizontal]
type:: dict
example::
+
[source,yaml]
----
clusterRoles:
  my-admin: ['my-admin', 'test-admin']
  special-role: special-role
----

`ClusterRoles` excluded from all namespace policies.
Must consist of entries like `my-admin: ['my-admin', 'test-admin']` or `my-admin: 'my-admin'`.

== `bypassNamespaceRestrictions.subjects`

[horizontal]
type:: dict
example::
+
[source,yaml]
----
subjects:
  argocd:
    kind: ServiceAccount
    name: argocd-application-controller
    namespace: syn-argocd
----

`ServiceAccount`, `User` or `Group` (chosen by `kind:`) excluded from all namespace policies.

== `generatedDefaultRoleBindingInNewNamespaces.clusterRoleName`

[horizontal]
type:: string
default:: `admin`

The `ClusterRole` name to which the requesting user account gets a new `RoleBinding` to.

== `generatedDefaultRoleBindingInNewNamespaces.bindingName`

[horizontal]
type:: string
default:: `organization-admin`

The `metadata.name` of the `RoleBinding` that gets generated in the new `Namespace` created by the user.
The role binding is only created upon Namespace creation, it doesn't get synchronized.

== `generatedNamespaceOwnerRole.name`

[horizontal]
type:: string
default:: `namespace-owner`

The `Role` and `RoleBinding` name for the role that allows users to edit the new `Namespace`

== `generatedResourceQuota`

[horizontal]
type:: dict

A key-value map defining `ResourceQuota` objects.
Each entry will generate a `ResourceQuota` with the key as its name.

=== `generatedResourceQuota[name].synchronize`

[horizontal]
type:: bool
default:: `true`

Whether the created `ResourceQuota` is kept in sync.
If set to `false` the created `ResourceQuota` can be modified.

[WARNING]
====
There is a bug in `kyverno` up until `v1.4.2`.
The bug has been fixed, but as of writing this the fix hasn't been released.
The bug will cause the `ResourceQuota` to be updated if the `Namespace` or `ClusterPolicy` changes, even if `synchronize` has been disabled.
====

=== `generatedResourceQuota[name].spec`

[horizontal]
type:: dict

The desired contents of field `spec` of the ResourceQuota that should be generated.
The component doesn't validate the contents of this field.
See the Kubernetes https://kubernetes.io/docs/concepts/policy/resource-quotas/[Resource Quota documentation] for supported configurations.

== `generatedLimitRange.name`

[horizontal]
type:: string
default:: `organization`

The `metadata.name` of the `LimitRange` that gets generated in the new `Namespace` created by the user.

== `generatedResourceQuota.synchronize`

[horizontal]
type:: bool
default:: `true`

Whether the created `LimitRange` is kept in sync.
If set to `false` the created `LimitRange` can be modified.

[WARNING]
====
There is a bug in `kyverno` up until `v1.4.2`.
The bug has been fixed, but as of writing this the fix hasn't been released.
The bug will cause the `LimitRange` to be updated if the `Namespace` or `ClusterPolicy` changes, even if `synchronize` has been disabled.
====

== `generatedLimitRange.limits`

[horizontal]
type:: dict
example::
+
[source,yaml]
----
limits:
  "Container":
    max:
      memory: "4G"
    min:
      memory: "4Mi"
  "PersistentVolumeClaim":
    max:
      storage: 2Gi
    min:
      storage: 1Gi
----

A key-value map defining limits for different `Types`.


The example above will reject any PVC smaller than `1Gi` or larger than `2Gi`.
It will also reject any container requesting more than `4G` of memory or less than `4Mi`.


Consult https://kubernetes.io/docs/concepts/policy/limit-range/[the official Kubernetes documentation] on how to configure these `limits`.

== `disallowDockerBuildStrategy`

[horizontal]
type:: boolean
default:: `true`

Creating https://docs.openshift.com/container-platform/4.7/cicd/builds/build-strategies.html#builds-strategy-docker-build_build-strategies[build strategies using Docker] is disallowed.

== `projectTemplate`

Configuration options for the OpenShift default project template.

=== `projectTemplate.enabled`

[horizontal]
type:: boolean
default:: `false`

This parameter controls whether the component deploys and enables a custom default project template.


=== `projectTemplate.objects`

[horizontal]
type:: dict
default::
+
[source,yaml]
----
project:
  apiVersion: project.openshift.io/v1
  kind: Project
  metadata:
    annotations:
      openshift.io/description: '\${PROJECT_DESCRIPTION}'
      openshift.io/display-name: '\${PROJECT_DISPLAYNAME}'
      openshift.io/requester: '\${PROJECT_REQUESTING_USER}'
    name: '\${PROJECT_NAME}'
----

The contents of this dict are used to populate field `objects` of the OpenShift template object.
The keys in the dict are ignored, but can be used in the configuration hierarchy to change existing template objects.
Setting a key to value `null` removes the object from the resulting template.

To avoid Commodore trying to interpret template parameters, escape them with `\${PARAM}` as shown in the default value.
Any parameters used in the template objects must be defined in component parameter `projectTemplate.parameters`.

NOTE: OpenShift requires that the default template contains at least one object of type `Project`.

=== `projectTemplate.parameters`

[horizontal]
type:: dict
default::
+
[source,yaml]
----
PROJECT_NAME: {}
PROJECT_DISPLAYNAME: {}
PROJECT_DESCRIPTION: {}
PROJECT_ADMIN_USER: {}
PROJECT_REQUESTING_USER: {}
----

The contents of this dict are used to populate field `parameters` of the OpenShift template object.

The field `parameters` in the template object is a list of objects, see the https://docs.openshift.com/container-platform/latest/openshift_images/using-templates.html#templates-writing_using-templates[OpenShift documentation].
The component transforms the entries of this component parameter into objects by using the key as field `name` of the resulting object and merging it with the provided value.
Users can remove parameters by setting value `null`.

== `runOnceActiveDeadlineSeconds`

Configuration for the cluster policy which ensures that `.spec.activeDeadlineSeconds` is set for all "runonce" pods.
"Runonce" pods are pods which have `.spec.restartPolicy` set to `OnFailure` or `Never`.

=== `runOnceActiveDeadlineSeconds.defaultActiveDeadlineSeconds`

[horizontal]
type:: int
default:: `1800`

This parameter gives the default value for `.spec.activeDeadlineSeconds` which is added to "runonce" pods which don't have the field set already.

=== `runOnceActiveDeadlineSeconds.overrideAnnotationKey`


[horizontal]
type:: string
default:: `appuio.io/active-deadline-seconds-override`

The key of the namespace annotation which users can use to override the global default value for `.spec.activeDeadlineSeconds`.
